#!/usr/bin/env bash
# A script that:
#+ Indefinitely writes "I am alive!" to the file /tmp/my_process
#+ In between every I am alive! message, pauses for 2 seconds.

FILE=/tmp/my_process
sudo touch $FILE

while true; do
sudo bash -c "echo \"I am alive!\" >> $FILE"
sleep 2
done
