#!/usr/bin/env bash
#  displays the content of the file "/etc/passwd" using the while loop;
#+ only displays the: username, user id and Home directory path for the user.

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd
