#!/usr/bin/env bash
# A script displaying "Best School" 10 times, prints hi on 9th
#+ but for the 9th iteration, displays "Best School" and then Hi on a new line.

i=0

while ((i < 10))
do
	echo "Best School"
	((i++))
	if ((i == 9))
	then
		echo "Hi"
	fi
done
