#!/usr/bin/env bash
# A bash script that Displays the content of the current directory:
#+ In a list format
#+ Where only the part of the name after the first dash is displayed.

current_directory=$("ls")
for i in $current_directory;
do
	echo "$i" | cut -d '-' -f2
done

